@extends('layouts.app')

@section('content')
@php
    $totalTasks = $tasks->count();
    $completionRate = $totalTasks > 0 ? round(($completedCount / $totalTasks) * 100) : 0;
@endphp

<main class="py-8 lg:py-12">
    <section class="relative overflow-hidden rounded-[2rem] bg-ink px-6 py-7 text-white shadow-soft sm:px-9 sm:py-9 lg:px-11">
        <div class="absolute -right-20 -top-24 h-72 w-72 rounded-full border-[35px] border-[#76539a]/30"></div>
        <div class="absolute -bottom-28 right-20 h-64 w-64 rounded-full border-[18px] border-[#dfc8ff]/10"></div>
        <div class="relative flex flex-col justify-between gap-8 md:flex-row md:items-center">
            <div class="fade-up max-w-xl"><p class="text-[11px] font-bold uppercase tracking-[.24em] text-lime">Your workspace</p><h1 class="mt-3 text-4xl font-bold leading-tight tracking-[-.04em] sm:text-5xl">Turn plans into progress.</h1><p class="mt-4 max-w-lg text-sm leading-6 text-[#d5c9df]">A focused space for the things you want to finish, one clear step at a time.</p></div>
            <div class="flex shrink-0 items-center gap-5"><div class="flex h-28 w-28 items-center justify-center rounded-full" style="background: conic-gradient(#dfc8ff {{ $completionRate }}%, #58466b {{ $completionRate }}% 100%)"><div class="flex h-20 w-20 flex-col items-center justify-center rounded-full bg-ink"><span class="text-2xl font-bold">{{ $completionRate }}%</span><span class="text-[9px] uppercase tracking-wider text-[#c2b3cf]">complete</span></div></div><div><p class="text-sm font-semibold">{{ $completedCount }} of {{ $totalTasks }}</p><p class="mt-1 text-xs text-[#b9aac5]">tasks finished</p></div></div>
        </div>
    </section>

    <section class="mt-8 grid gap-8 lg:grid-cols-[minmax(0,1fr)_370px]">
        <div class="order-2 lg:order-1">
            <div class="mb-5 flex items-end justify-between gap-4"><div><p class="text-[11px] font-bold uppercase tracking-[.2em] text-moss">Overview</p><h2 class="mt-1 text-2xl font-bold tracking-tight text-ink">Your task flow</h2></div><span class="text-xs font-semibold text-moss">{{ now()->format('M d, Y') }}</span></div>
            <div class="mb-7 grid grid-cols-3 gap-2 sm:gap-3"><div class="rounded-2xl border border-line bg-white p-4 shadow-sm"><span class="mb-5 flex h-8 w-8 items-center justify-center rounded-lg bg-[#eee3ff] text-sm text-[#755395]">○</span><p class="text-[10px] font-bold uppercase tracking-wider text-moss">Pending</p><p class="mt-1 text-2xl font-bold text-ink">{{ $pendingCount }}</p></div><div class="rounded-2xl border border-line bg-white p-4 shadow-sm"><span class="mb-5 flex h-8 w-8 items-center justify-center rounded-lg bg-[#e5f6ca] text-sm text-[#628039]">✓</span><p class="text-[10px] font-bold uppercase tracking-wider text-moss">Completed</p><p class="mt-1 text-2xl font-bold text-ink">{{ $completedCount }}</p></div><div class="rounded-2xl border border-line bg-white p-4 shadow-sm"><span class="mb-5 flex h-8 w-8 items-center justify-center rounded-lg bg-[#fff0f6] text-sm text-coral">!</span><p class="text-[10px] font-bold uppercase tracking-wider text-moss">Overdue</p><p class="mt-1 text-2xl font-bold text-coral">{{ $overdueCount }}</p></div></div>
            <div class="mb-4 flex items-center justify-between"><h3 class="text-sm font-bold text-ink">All tasks</h3><span class="rounded-full bg-[#eee3ff] px-3 py-1 text-[10px] font-bold uppercase tracking-wider text-[#725493]">{{ $totalTasks }} total</span></div>
            @forelse ($tasks as $task)
                <article class="task-row fade-up mb-3 rounded-2xl border border-line bg-white p-4 shadow-sm sm:p-5" style="animation-delay: {{ $loop->index * 60 }}ms"><div class="flex items-start gap-4"><form method="POST" action="{{ route('tasks.toggle', $task) }}" class="pt-1">@csrf @method('PATCH')<button type="submit" class="flex h-6 w-6 items-center justify-center rounded-lg border-2 {{ $task->status === 'Completed' ? 'border-ink bg-ink text-lime' : 'border-[#cdbddc] text-transparent hover:border-ink' }}" aria-label="Mark {{ $task->status === 'Completed' ? 'pending' : 'completed' }}">✓</button></form><div class="min-w-0 flex-1"><div class="flex flex-wrap items-center gap-2"><h3 class="font-semibold {{ $task->status === 'Completed' ? 'text-moss line-through' : 'text-ink' }}">{{ $task->task_name }}</h3><span class="rounded-md px-2 py-1 text-[10px] font-bold uppercase tracking-wider {{ $task->status === 'Completed' ? 'bg-[#eee3ff] text-[#725493]' : 'bg-[#fff0f6] text-coral' }}">{{ $task->status }}</span></div>@if ($task->description)<p class="mt-2 text-sm leading-6 text-moss">{{ $task->description }}</p>@endif<div class="mt-3 flex items-center gap-1.5 text-xs font-medium {{ $task->due_date?->isPast() && $task->status === 'Pending' ? 'text-coral' : 'text-moss' }}"><svg class="h-3.5 w-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="3" y="4" width="18" height="18" rx="2"/><path d="M16 2v4M8 2v4M3 10h18"/></svg>{{ $task->due_date ? $task->due_date->format('M j, Y') : 'No deadline' }}@if ($task->due_date?->isPast() && $task->status === 'Pending')<span>· overdue</span>@endif</div></div><div class="flex shrink-0 items-center gap-1"><a href="{{ route('tasks.edit', $task) }}" class="rounded-lg p-2 text-moss hover:bg-[#f3edff]" aria-label="Edit {{ $task->task_name }}"><svg class="h-4 w-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M12 20h9"/><path d="M16.5 3.5a2.12 2.12 0 0 1 3 3L8 18l-4 1 1-4Z"/></svg></a><form method="POST" action="{{ route('tasks.destroy', $task) }}" onsubmit="return confirm('Delete this task?')">@csrf @method('DELETE')<button type="submit" class="rounded-lg p-2 text-[#a9b2aa] hover:bg-[#fff0f6] hover:text-coral" aria-label="Delete {{ $task->task_name }}"><svg class="h-4 w-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M3 6h18M8 6V4h8v2M19 6l-1 14H6L5 6M10 11v5M14 11v5"/></svg></button></form></div></div></article>
            @empty
                <div class="rounded-2xl border border-dashed border-[#cdbddc] bg-white px-6 py-16 text-center shadow-sm"><div class="mx-auto flex h-12 w-12 items-center justify-center rounded-2xl bg-lime text-ink">✦</div><h3 class="mt-5 text-xl font-bold">Your board is clear.</h3><p class="mx-auto mt-2 max-w-sm text-sm leading-6 text-moss">Add your first task from the panel and give your next win a place to land.</p></div>
            @endforelse
        </div>
        <aside class="order-1 lg:order-2"><div class="rounded-[2rem] border border-[#d8c6ea] bg-[#f5effc] p-6 shadow-sm sm:p-7"><div class="flex items-start justify-between"><div><p class="text-[11px] font-bold uppercase tracking-[.2em] text-[#8663a4]">Quick capture</p><h2 class="mt-2 text-3xl font-bold tracking-tight text-ink">Add a task.</h2><p class="mt-2 text-sm leading-5 text-moss">Give your next priority a clear place.</p></div><span class="text-3xl font-light text-[#9b75ba]">+</span></div><form method="POST" action="{{ route('tasks.store') }}" class="mt-7 space-y-4">@csrf @include('tasks.partials.form', ['buttonLabel' => 'Add to board'])</form></div></aside>
    </section>
</main>
@endsection
